DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  description TEXT NOT NULL
);

DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  image TEXT,
  categoryId INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  userId INTEGER REFERENCES users(id) ON DELETE CASCADE,
  productLocation NUMERIC [],
  location VARCHAR(255),
  condition VARCHAR(255),
  color VARCHAR(255),
  createdAt TIMESTAMP WITHOUT TIME ZONE
);

DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE comments (
  id SERIAL PRIMARY KEY NOT NULL,
  userId INTEGER REFERENCES users(id) ON DELETE CASCADE,
  productId INTEGER REFERENCES products(id) ON DELETE CASCADE,
  comment TEXT,
  createdAt TIMESTAMP WITHOUT TIME ZONE
);

DROP TABLE IF EXISTS favourites CASCADE;

CREATE TABLE favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  userId INTEGER REFERENCES users(id) ON DELETE CASCADE,
  productId INTEGER REFERENCES products(id) ON DELETE CASCADE
);



